[package]
name = "kvs"
version = "0.1.0"
authors = ["William Mbotta <sergembotta@mamiloo.org>"]
description = "A key-value store"
edition = "2018"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"

[dependencies]
structopt = "0.3.14"
